[package]
name = "rusty_dns_server"
version = "0.1.0"
authors = ["Tristan Burgess <tburgessdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
